version: '3'
services:

  carsguide:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carsguide
    environment:
      SERVICE_NAME: carsguide
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - carsguide-network

  db:
    image: mysql:5.7
    container_name: db
    command: mysqld --skip-ssl
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_cars_guide
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mydata:/var/lib/mysql/
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - carsguide-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - carsguide-network

networks:
  carsguide-network:
    driver: bridge

volumes:
  mydata:
    driver: local
